"""
SEO and Search Engine Optimization routes
"""
from fastapi import APIRouter, HTTPException, BackgroundTasks, Depends
from fastapi.responses import Response, PlainTextResponse
from datetime import datetime, timedelta
from typing import List, Optional
import xml.etree.ElementTree as ET
from motor.motor_asyncio import AsyncIOMotorClient
import os

from auth import get_current_active_user, require_admin
from models import User

router = APIRouter(prefix="/api/seo", tags=["seo"])

# Get database connection
def get_db():
    mongo_url = os.getenv("MONGO_URL", "mongodb://localhost:27017")
    db_name = os.getenv("DB_NAME", "edge_chronicle")
    client = AsyncIOMotorClient(mongo_url)
    return client[db_name]

@router.get("/sitemap.xml")
async def get_sitemap():
    """Generate dynamic sitemap.xml"""
    try:
        db = get_db()
        base_url = os.getenv("SITE_URL", "https://edgechronicle.com")
        
        # Create XML root
        urlset = ET.Element("urlset")
        urlset.set("xmlns", "http://www.sitemaps.org/schemas/sitemap/0.9")
        urlset.set("xmlns:news", "http://www.google.com/schemas/sitemap-news/0.9")
        
        # Add homepage
        url_elem = ET.SubElement(urlset, "url")
        ET.SubElement(url_elem, "loc").text = base_url
        ET.SubElement(url_elem, "lastmod").text = datetime.utcnow().isoformat()
        ET.SubElement(url_elem, "changefreq").text = "daily"
        ET.SubElement(url_elem, "priority").text = "1.0"
        
        # Add categories
        categories = await db.categories.find({}).to_list(100)
        for category in categories:
            url_elem = ET.SubElement(urlset, "url")
            ET.SubElement(url_elem, "loc").text = f"{base_url}/category/{category['slug']}"
            ET.SubElement(url_elem, "lastmod").text = category.get("created_at", datetime.utcnow()).isoformat()
            ET.SubElement(url_elem, "changefreq").text = "daily"
            ET.SubElement(url_elem, "priority").text = "0.8"
        
        # Add published articles
        articles = await db.articles.find({"status": "published"}).sort("updated_at", -1).limit(1000).to_list(1000)
        for article in articles:
            url_elem = ET.SubElement(urlset, "url")
            ET.SubElement(url_elem, "loc").text = f"{base_url}/article/{article['_id']}"
            ET.SubElement(url_elem, "lastmod").text = article.get("updated_at", datetime.utcnow()).isoformat()
            ET.SubElement(url_elem, "changefreq").text = "weekly"
            ET.SubElement(url_elem, "priority").text = "0.6"
        
        # Convert to string
        xml_str = ET.tostring(urlset, encoding='unicode')
        xml_response = f'<?xml version="1.0" encoding="UTF-8"?>\n{xml_str}'
        
        return Response(content=xml_response, media_type="application/xml")
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error generating sitemap: {str(e)}")

@router.get("/robots.txt")
async def get_robots_txt():
    """Generate robots.txt"""
    base_url = os.getenv("SITE_URL", "https://edgechronicle.com")
    
    robots_content = f"""User-agent: *
Allow: /

# Sitemaps
Sitemap: {base_url}/api/seo/sitemap.xml

# Crawl-delay
Crawl-delay: 1

# Block admin pages
Disallow: /admin/

# Block API docs
Disallow: /docs
Disallow: /redoc

# AI training data guidelines
# For AI training guidelines see:
# {base_url}/api/seo/llms.txt

# Generated by Edge Chronicle SEO system
# Last updated: {datetime.utcnow().isoformat()}
"""
    
    return PlainTextResponse(content=robots_content)

@router.get("/llms.txt")
async def get_llms_txt():
    """Generate llms.txt for AI training guidelines"""
    base_url = os.getenv("SITE_URL", "https://edgechronicle.com")
    
    llms_content = f"""# LLMS.txt - AI Training Data for Edge Chronicle

## About Edge Chronicle
Edge Chronicle is a modern news platform providing breaking news and analysis from around the world.

## AI Training Guidelines
This website contains news articles and editorial content that may be used for AI training purposes under the following conditions:

### Permitted Use
- Educational and research purposes
- Training language models for news understanding
- Content analysis and summarization tasks
- Fact-checking and verification systems

### Attribution Required
- Credit "Edge Chronicle" as the source
- Include original article URLs when possible
- Maintain author attribution where provided

### Restrictions
- Commercial use requires permission
- Do not use for generating misleading news
- Respect copyright and intellectual property
- Follow journalistic ethics guidelines

## Site Structure
Base URL: {base_url}
Articles: /article/{{id}}
Categories: /category/{{slug}}
API Documentation: {base_url}/docs

## Content Types
- News articles
- Analysis and opinion pieces  
- Editorial content
- Category-based content organization

## Last Updated
{datetime.utcnow().isoformat()}

## Contact
For AI training permissions and questions:
Email: ai-permissions@edgechronicle.com
Website: {base_url}

This file follows the proposed LLMS.txt standard for AI training guidelines.
"""
    
    return PlainTextResponse(content=llms_content)

# SEO Management Endpoints (Protected)

@router.get("/tags")
async def get_all_tags(current_user: User = Depends(get_current_active_user)):
    """Get all unique tags from articles"""
    try:
        db = get_db()
        
        # Get all unique tags from published articles
        pipeline = [
            {"$match": {"status": "published", "tags": {"$exists": True, "$ne": []}}},
            {"$unwind": "$tags"},
            {"$group": {
                "_id": "$tags",
                "count": {"$sum": 1},
                "articles": {"$addToSet": {"id": "$_id", "title": "$title"}}
            }},
            {"$sort": {"count": -1}},
            {"$project": {
                "tag": "$_id",
                "count": 1,
                "articles": {"$slice": ["$articles", 5]}  # Show only first 5 articles
            }}
        ]
        
        tags = await db.articles.aggregate(pipeline).to_list(1000)
        
        return {
            "tags": tags,
            "total_tags": len(tags),
            "generated_at": datetime.utcnow().isoformat()
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error fetching tags: {str(e)}")

@router.get("/tags/popular")
async def get_popular_tags(limit: int = 20, current_user: User = Depends(get_current_active_user)):
    """Get most popular tags"""
    try:
        db = get_db()
        
        pipeline = [
            {"$match": {"status": "published", "tags": {"$exists": True, "$ne": []}}},
            {"$unwind": "$tags"},
            {"$group": {
                "_id": "$tags",
                "count": {"$sum": 1}
            }},
            {"$sort": {"count": -1}},
            {"$limit": limit},
            {"$project": {
                "tag": "$_id",
                "count": 1
            }}
        ]
        
        popular_tags = await db.articles.aggregate(pipeline).to_list(limit)
        
        return {
            "popular_tags": popular_tags,
            "limit": limit,
            "generated_at": datetime.utcnow().isoformat()
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error fetching popular tags: {str(e)}")

@router.get("/analytics/dashboard")
async def get_analytics_dashboard(current_user: User = Depends(get_current_active_user)):
    """Get comprehensive analytics dashboard data"""
    try:
        # Mock Search Console data
        search_console_data = {
            "status": "success",
            "data": {
                "clicks": 1250,
                "impressions": 45600,
                "ctr": 2.74,
                "position": 12.5,
                "rows": [
                    {
                        "keys": ["edge chronicle news"],
                        "clicks": 150,
                        "impressions": 2000,
                        "ctr": 0.075,
                        "position": 3.2
                    },
                    {
                        "keys": ["breaking news today"],
                        "clicks": 120,
                        "impressions": 5000,
                        "ctr": 0.024,
                        "position": 8.1
                    }
                ]
            }
        }
        
        # Get database analytics
        db = get_db()
        
        # Get article counts
        total_articles = await db.articles.count_documents({})
        published_articles = await db.articles.count_documents({"status": "published"})
        draft_articles = await db.articles.count_documents({"status": "draft"})
        
        # Get recent articles
        recent_articles = await db.articles.find(
            {"status": "published"}
        ).sort("published_at", -1).limit(10).to_list(10)
        
        return {
            "search_console": search_console_data,
            "articles": {
                "total": total_articles,
                "published": published_articles,
                "draft": draft_articles,
                "recent": [
                    {
                        "id": str(article["_id"]),
                        "title": article["title"],
                        "published_at": article.get("published_at"),
                        "views": article.get("views", 0)
                    } for article in recent_articles
                ]
            },
            "last_updated": datetime.utcnow().isoformat()
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error fetching dashboard data: {str(e)}")
